services:
  mysqldb:
    image: mysql:8.0
    cap_add:
      - SYS_NICE 
    container_name: mysqlcontainer
    command: --authentication_policy=mysql_native_password
    restart: unless-stopped
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/0_init.sql
      - $HOME/database:/var/lib/mysql
    ports:
      - 3308:3306
    expose:
      - 3306
    environment:
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: 12345
      SERVICE_NAME: mysqldb
      SERVICE_TAGS: prod
    healthcheck:
      test: ["CMD-SHELL", 'mysql --database=$$MYSQL_DATABASE --password=$$MYSQL_ROOT_PASSWORD --execute="USE Hamburgueria"']
      interval: 30s
      timeout: 10s
      retries: 4
    networks:
      - internalnet
  nodeapp:
    container_name: nodeappcontainer
    build: .
    image: nodeapp:v1
    volumes:
      - $HOME/nodeapp:/codigo
    ports:
      - 3000:3000
    expose:
      - 3000
    environment:
      DB_HOST: mysqldb
      DB_PORT: 3306
      DB_USER: 'root'
      DB_PASSWORD: '12345'
      DB_NAME: Hamburgueria
      SERVICE_NAME: nodeappservice
      SERVICE_TAGS: prod
      SERVER_PORT: 3000
    depends_on:
      mysqldb:
       condition: service_healthy
    restart: on-failure
    networks:
      - internalnet
networks:
  internalnet:
    driver: bridge